#!/usr/bin/env bash

WIFI_STATE=$(nmcli radio wifi)

# INFO: First argument is an Image, second is the service and the third is the state
notify_user() {
	notify-send -t 1800 -u normal -i "$1" "$2: $3"
}

wifi() {
	if [[ "$WIFI_STATE" == "enabled" ]]; then
		nmcli radio wifi off
		notify_user "$WIFI_ICON" "Wifi" "OFF"
	elif [[ "$WIFI_STATE" == "disabled" ]]; then
		nmcli radio wifi on
		notify_user "$WIFI_ICON" "Wifi" "ON"
	fi
}

wifi
